### ISSUE TITLE
Absolute paths in includes

### ISSUE THREAD

**Issue by igor-zt** [shevek/jcpp#21]
JCPP cannot handle absolute paths in include directives. They are treated as relative. For example, 
#include "/home/me/test.h"
will not work. On the other hand
#include "/test.h"
will work looking for the file in the current directory.

**Comment by igor-zt** [comment]
#include </usr/include/stdio.h>

int main (int argc, char * argv []) {
    printf ("Hello world!\n");
    return 0;
}

**Comment by shevek** [comment]
I suspect the "correct" answer to this is to throw out jcpp's VFS implementation and use the new java.nio.file code.

**Comment by shevek** [comment]
Just to confirm, you are on at least Java 1.7?

**Comment by shevek** [comment]
There's an absolute path patch in #7 too

**Comment by shevek** [comment]
@ochafik I'm looking at checking whether path is absolute at the top of `include(String parent, int line, String name, boolean quoted, boolean next)` as if it's absolute, it doesn't matter whether it's quoted or anglebracketed.

**Comment by igor-zt** [comment]
Hi Shevek,

Yes, I am on Java 1.7.

Please do not abandon the VFS interface. I really need it. And,
yes, you can place a check for absolute path to the top of your 1st
level "include" routine. This should go through VFS as well. You may add
something like isAbsolute().

Thanks,
Igor

**Comment by shevek** [comment]
Will the java.nio.file code (which is a standard VFS interface in the JDK) suffice? Is it possible for you to implement your virtual filesystem using that? Then we can both use things like https://github.com/google/jimfs which is a set of filesystems based on that API.
